service: trainee-things
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'lambda:UpdateFunctionCode'
          Resource: arn:aws:lambda:eu-central-1:*:*

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  calc:
    handler: calculation_handler.calculate_response
    events:
      - httpApi:
          path: /calculate
          method: post
